test:
  workers:
    type: local
    number: 5
  rounds:
    - label: Create
      txNumber: 200
      rateControl:
        type: maximum-rate
        opts:
          tps: 100
          step: 5
          sampleInterval: 20
          includeFailed: true
      workload:
        module: benchmarks/scenario/createCar.js
    - label: Create
      txNumber: 400
      rateControl:
        type: maximum-rate
        opts:
          tps: 100
          step: 5
          sampleInterval: 20
          includeFailed: true
      workload:
        module: benchmarks/scenario/createCar.js     
    - label: Create
      txNumber: 600
      rateControl:
        type: maximum-rate
        opts:
          tps: 100
          step: 5
          sampleInterval: 20
          includeFailed: true
      workload:
        module: benchmarks/scenario/createCar.js
    - label: Create
      txNumber: 800
      rateControl:
        type: maximum-rate
        opts:
          tps: 100
          step: 5
          sampleInterval: 20
          includeFailed: true
      workload:
        module: benchmarks/scenario/createCar.js        
    - label: Create
      txNumber: 1000
      rateControl:
        type: maximum-rate
        opts:
          tps: 100
          step: 5
          sampleInterval: 20
          includeFailed: true
      workload:
        module: benchmarks/scenario/createCar.js        