test:
  workers:
    type: local
    number: 5
  rounds:
    - label: Query
      txNumber: 200
      rateControl:
        type: maximum-rate
        opts:
          tps: 100
          step: 5
          sampleInterval: 20
          includeFailed: true
      workload:
        module: benchmarks/scenario/queryCar.js
        arguments:
          assets: 10
    - label: Query
      txNumber: 400
      rateControl:
        type: maximum-rate
        opts:
          tps: 100
          step: 5
          sampleInterval: 20
          includeFailed: true
      workload:
        module: benchmarks/scenario/queryCar.js
        arguments:
          assets: 10   
    - label: Query
      txNumber: 600
      rateControl:
        type: maximum-rate
        opts:
          tps: 100
          step: 5
          sampleInterval: 20
          includeFailed: true
      workload:
        module: benchmarks/scenario/queryCar.js
        arguments:
          assets: 10                    
    - label: Query
      txNumber: 600
      rateControl:
        type: maximum-rate
        opts:
          tps: 100
          step: 5
          sampleInterval: 20
          includeFailed: true
      workload:
        module: benchmarks/scenario/queryCar.js
        arguments:
          assets: 10    
    - label: Query
      txNumber: 800
      rateControl:
        type: maximum-rate
        opts:
          tps: 100
          step: 5
          sampleInterval: 20
          includeFailed: true
      workload:
        module: benchmarks/scenario/queryCar.js
        arguments:
          assets: 10                      
    - label: Query
      txNumber: 1000
      rateControl:
        type: maximum-rate
        opts:
          tps: 100
          step: 5
          sampleInterval: 20
          includeFailed: true
      workload:
        module: benchmarks/scenario/queryCar.js
        arguments:
          assets: 10             